apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Namespace }}-docker-config
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.secrets.registry.dockerconfigjson }}
  config.json: {{ .Values.secrets.registry.configjson }}
{{/*  .dockerconfigjson: {{ .Values.secrets.registry.dockerconfigjson | b64enc }}*/}}
{{/*  config.json: {{ .Values.secrets.registry.configjson | b64enc }}*/}}

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Namespace }}-minio
type: Opaque
data:
  accessKey: {{ .Values.secrets.minio.accesKey }}
  secretKey: {{ .Values.secrets.minio.secretKey }}
  minioApi: {{ .Values.secrets.minio.api}}

{{/*  accessKey: {{ .Values.secrets.minio.accesKey | b64enc }}*/}}
{{/*  secretKey: {{ .Values.secrets.minio.secretKey | b64enc }}*/}}
{{/*  minioApi: {{ .Values.secrets.minio.api | b64enc }}*/}}
