apiVersion: v1
entries:
  datagrok:
  - apiVersion: v2
    appVersion: 1.19.x
    created: "2024-09-16T13:25:48.252765243Z"
    dependencies:
    - name: datagrok_grok_connect
      repository: '@datagrok'
      version: 1.0.0
    - name: datagrok_jkg
      repository: '@datagrok'
      version: 1.0.0
    - name: datagrok_jupyter_notebook
      repository: '@datagrok'
      version: 1.0.0
    - name: datagrok_grok_spawner
      repository: ""
      version: 1.0.0
    description: A Helm chart for Kubernetes
    digest: 80a3590d013fea557f641196e01542098f7c870666ef6ec460c361b22f31809f
    name: datagrok
    type: application
    urls:
    - datagrok-1.0.3.tgz
    version: 1.0.3
  datagrok_grok_connect:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2024-09-16T13:25:48.25299459Z"
    description: A Helm chart for Kubernetes
    digest: 75e0fb36e42549b54253fec164d6052e82d99e7648852f69d6c9606f4f7e7923
    icon: https://awsmp-logos.s3.amazonaws.com/seller-rd56pvqdccmwk/d29ebfef5392118b01bee04677722cae.png
    name: datagrok_grok_connect
    type: application
    urls:
    - datagrok_grok_connect-1.0.0.tgz
    version: 1.0.0
  datagrok_grok_spawner:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2024-09-16T13:25:48.257737473Z"
    dependencies:
    - name: minio
      repository: ""
      version: 14.6.22
    description: A Helm chart for Kubernetes
    digest: 286f512a4879b0407d818290b970d6b32f8d3f6e426c16b58715cdcc2f9e8bfa
    icon: https://awsmp-logos.s3.amazonaws.com/seller-rd56pvqdccmwk/d29ebfef5392118b01bee04677722cae.png
    name: datagrok_grok_spawner
    type: application
    urls:
    - datagrok_grok_spawner-1.0.0.tgz
    version: 1.0.0
  datagrok_jkg:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2024-09-16T13:25:48.258051887Z"
    description: A Helm chart for Kubernetes
    digest: e3b3ead5f5c6dc9345098748bd34f068a2f2b03575dafc4fe8912c92e0cd5b71
    icon: https://awsmp-logos.s3.amazonaws.com/seller-rd56pvqdccmwk/d29ebfef5392118b01bee04677722cae.png
    name: datagrok_jkg
    type: application
    urls:
    - datagrok_jkg-1.0.0.tgz
    version: 1.0.0
  datagrok_jupyter_notebook:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2024-09-16T13:25:48.258295009Z"
    description: A Helm chart for Kubernetes
    digest: 0bba9d775b6e18dbcf4dc793fd26b00469551678afe82628a1f3226c40632694
    icon: https://awsmp-logos.s3.amazonaws.com/seller-rd56pvqdccmwk/d29ebfef5392118b01bee04677722cae.png
    name: datagrok_jupyter_notebook
    type: application
    urls:
    - datagrok_jupyter_notebook-1.0.0.tgz
    version: 1.0.0
generated: "2024-09-16T13:25:48.247681393Z"
