apiVersion: v1
kind: Service
metadata:
  labels:
    service: grok-spawner
  name: grok-spawner
  namespace: datagrok
spec:
  ports:
    - name: "grok-spawner"
      port: 8000
      targetPort: 8000
  selector:
    service: grok-spawner
