servers:
  dev:
    url: https://dev.datagrok.ai/api
    key: 'khHEGLGXhD'
  public:
    url: https://public.datagrok.ai/api
    key: ''
  local:
    url: http://localhost:8080//api
    key: EFA1QT0AbP
default: public
