version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "15:05"
    labels:
      - "dependencies"
      - "npm"
    open-pull-requests-limit: 10
    title: "Update {{#dependencies}} {{name}}: From {{oldVersion}}: To {{newVersion}} {{/dependencies}}"
