{{- if .Values.enabled -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-grok-parameters-configmap
data: 
  GROK_PARAMETERS: |-
    {
      {{- $len := sub (len .Values.grok_parameters) 1 }}
      {{- $count := 1 }}
      {{- range $key, $value := .Values.grok_parameters }}
      {{ if le $count $len }}
        {{- if kindIs "string" $value }}
          {{- $key | quote | indent 2}}: {{ $value | quote }},
        {{- else }}
          {{- $key | quote | indent 2}}: {{ $value }},
        {{- end }}
        {{- $count = add $count 1 }}
      {{- else }}
        {{- if kindIs "string" $value }}
          {{- $key | quote | indent 2}}: {{ $value | quote }}
        {{- else }}
          {{- $key | quote | indent 2}}: {{ $value }}
        {{- end }}
        {{- $count = add $count 1 }}
      {{- $count = add $count 1 }}
      {{- end }}
      {{- end }}
      }
{{- end }}