apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: database
  name: datagrok-db
  namespace: datagrok
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
