apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: datagrok
  name: datagrok-data
  namespace: datagrok
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
