apiVersion: v1
kind: Service
metadata:
  namespace: datagrok
  labels:
    service: jupyter-notebook
  name: jupyter-notebook
spec:
  ports:
    - name: "helper"
      port: 5005
      targetPort: 5005
    - name: "notebook"
      port: 8889
      targetPort: 8889
  selector:
    service: jupyter-notebook
