apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: datagrok
  name: datagrok-cfg
  namespace: datagrok
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
