version: "3"
services:
  datagrok:
    privileged: true
    image: datagrok/datagrok:${DATAGROK_VERSION:-latest}
    environment:
      GROK_PARAMETERS: |
        {
          "deployDemo": false,
          "dbServer": "database",
          "db": "datagrok",
          "dbAdminLogin": "postgres",
          "dbAdminPassword": "postgres",
          "dbLogin": "dg",
          "dbPassword": "dg",
          "adminPassword": "admin",
          "adminDevKey": "admin",
          "isolatesCount": 2,
          "connectorsSettings": {
            "dataframeParsingMode":"New Process",
            "externalDataFrameCompress":true,
            "grokConnectHost":"grok_connect",
            "grokConnectPort":1234,
            "localFileSystemAccess":false,
            "sambaSpaceEscape":"none",
            "sambaVersion":"3.0"
          },
          "dockerSettings": {
            "grokSpawnerApiKey": "test-x-api-key",
            "grokSpawnerHost": "grok_spawner",
            "grokSpawnerPort": 8000,
            "imageBuildTimeoutMinutes": 30,
            "proxyRequestTimeout": 60000
          },
          "queueSettings": {
            "amqpHost": "rabbitmq",
            "amqpPassword": "guest",
            "amqpPort": 5672,
            "amqpUser": "guest",
            "pipeHost": "grok_pipe",
            "pipeKey": "test-key"
            }
          }
    ports:
      - "${DATAGROK_PORT:-8080}:8080/tcp"
    networks:
      datagrok:
        aliases:
          - datagrok
    depends_on:
      db:
        condition: service_healthy
        restart: false
    volumes:
      - datagrok_data:/home/grok/data
      - datagrok_cfg:/home/grok/cfg
      - type: bind
        source: ${FULL_PATH_TO_BUILD_JS_API:-./../js-api/../../xamgle/web/js/api}
        target: /home/grok/datagrok/html.build/web/js/api
    restart: unless-stopped
    profiles: ["all", "datagrok"]

volumes:
  datagrok_data:
  datagrok_cfg:

networks:
  datagrok:
