---
# Specifies the version of the AWS CloudFormation template format being used.
AWSTemplateFormatVersion: '2010-09-09'


# 'Mappings' section is used to define key-value pairs that can be reused throughout the template.
# Useful for separating environment- or region-specific values (e.g., AMI IDs, Docker image repositories, etc.).
Mappings:
  Images:
    Datagrok:
      domain: "docker.io"
      repo: "datagrok/datagrok"
    GrokConnect:
      domain: "docker.io"
      repo: "datagrok/grok_connect"
    GrokPipe:
      domain: "docker.io"
      repo: "datagrok/grok_pipe"
    Rabbitmq:
      domain: "docker.io"
      repo: "rabbitmq"
    GrokSpawner:
      domain: "docker.io"
      repo: "datagrok/grok_spawner"
    JKG:
      domain: "docker.io"
      repo: "datagrok/jupyter_kernel_gateway"
    JN:
      domain: "docker.io"
      repo: "datagrok/jupyter_notebook"
    Kaniko:
      domain: "gcr.io"
      repo: "kaniko-project/executor"
      version: "v1.12.1"
    Searchdomain:
      domain: "docker.io"
      repo: "docker/ecs-searchdomain-sidecar"
      version: "1.0"
    Smtp:
      domain: "docker.io"
      repo: "datagrok/smtp"
      version: "1.0.0"
