---
AWSTemplateFormatVersion: '2010-09-09'
Mappings:
  Images:
    Datagrok:
      domain: "709825985650.dkr.ecr.us-east-1.amazonaws.com"
      repo: "datagrok/datagrok"
    GrokConnect:
      domain: "709825985650.dkr.ecr.us-east-1.amazonaws.com"
      repo: "datagrok/grok_connect"
    GrokSpawner:
      domain: "709825985650.dkr.ecr.us-east-1.amazonaws.com"
      repo: "datagrok/grok_spawner"
    Jupyter:
      domain: "709825985650.dkr.ecr.us-east-1.amazonaws.com"
      repo: "datagrok/jupyter"
    GrokCompute:
      domain: "709825985650.dkr.ecr.us-east-1.amazonaws.com"
      repo: "datagrok/grok_compute"
    H2o:
      domain: "709825985650.dkr.ecr.us-east-1.amazonaws.com"
      repo: "datagrok/h2o"
    Kaniko:
      domain: "709825985650.dkr.ecr.us-east-1.amazonaws.com"
      repo: "datagrok/kaniko"
      version: "v1.12.1"
    Searchdomain:
      domain: "709825985650.dkr.ecr.us-east-1.amazonaws.com"
      repo: "datagrok/ecs-searchdomain-sidecar"
      version: "1.0"
    Smtp:
      domain: "709825985650.dkr.ecr.us-east-1.amazonaws.com"
      repo: "datagrok/smtp"
      version: "1.0.0"
