apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Namespace }}-{{ .Release.Name }}-sa

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Namespace }}-{{ .Release.Name }}-sa
rules:
  - apiGroups: ["*"]
    resources: ["pods", "services", "deployments", "configmaps", "secrets", "jobs", "pods/log"]  # Add other resources as needed
    verbs: ["create", "get", "update", "delete", "list", "watch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: resource-creator-binding
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Namespace }}-{{ .Release.Name }}-sa
roleRef:
  kind: Role
  name: {{ .Release.Namespace }}-{{ .Release.Name }}-sa
  apiGroup: rbac.authorization.k8s.io
