name: myenv
channels:
  - conda-forge
  - pytorch
dependencies:
  - python>=3.11
  - pip
  - pip:
      - -r requirements.txt
  - rdkit
  - joblib
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - boto3
  - gunicorn
  - Flask
  - chemprop=2.0.4
  - mkl=2024.0.0
  - cuda-version=12.4
  - cudatoolkit=12.4
  - cuDNN
  - pytorch>=2.1=*cuda*
  - torchvision=*=*_cu*
  - torchaudio=*=*_cu*
