name: myenv
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.9
  - pip
  - pip:
    - -r requirements.txt 
  - rdkit
  - joblib
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - boto3
  - Flask
  - chemprop
  - mkl
  - pytorch=1.10.0
  - torchvision=0.11.1
  - torchaudio=0.10.0
  - cudatoolkit=11.4