name: Help deployment

on:
  workflow_dispatch: {}
  push:
    paths:
      - 'help/**'
jobs:
  convert_md_to_html:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create entrypoint for pandoc
        run: |
          echo '#!/bin/sh' > entrypoint.sh;
          for f in help/**/*.md; do
            mkdir -p output/$(dirname ${f});
            echo "pandoc -f gfm -t html --output=/github/workspace/output/${f/.md/.html} \"${f}\"" >> entrypoint.sh;
          done;
          cat entrypoint.sh;
          ls -lah output;
      - uses: docker://pandoc/core:latest
        with:
          entrypoint: /bin/sh
          args: /github/workspace/entrypoint.sh
