name: "IaaC script Security Scan"

on:
  push:
    paths:
      - 'help/develop/admin/deploy/cloudformation/cloudformation.json'
  pull_request:
    paths:
      - 'help/develop/admin/deploy/cloudformation/cloudformation.json'

jobs:
  common-check:
    name: Common checks
    uses: ./.github/workflows/common_check.yaml
    with:
      run_trigger: ${{ github.event_name }}

  iac:
    needs: common-check
    runs-on: ubuntu-20.04
    if: needs.common-check.outputs.continue == 'true'
    name: Security check for IaaC scripts
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run contract with Snyk to check Infrastructure as Code files for issues
        uses: snyk/actions/iac@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high
          sarif: true
          file: 'help/develop/admin/deploy/cloudformation/cloudformation.json'
      - uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: snyk.sarif
