name: "IaaC script Security Scan"

on:
  push:
    paths:
      - 'help/develop/admin/deploy/cloudformation/cloudformation.json'
    branches:
      - 'master'
  pull_request:
    paths:
      - 'help/develop/admin/deploy/cloudformation/cloudformation.json'
    branches:
      - 'master'
jobs:
  process-merge-commit:
    runs-on: ubuntu-20.04
    outputs:
      merge_commit: ${{ steps.commit-details.outputs.is_merge_commit }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get commit details
        id: commit-details
        run: |
          if [[ $(git log -n 1 --pretty=%B) == *"Merge branch 'master'"* ]] || [[ $(git log -n 1 --pretty=%B) == *"Merge remote-tracking branch 'origin/master'"* ]]; then
            echo "is_merge_commit=true" >> $GITHUB_OUTPUT
          else
            echo "is_merge_commit=false" >> $GITHUB_OUTPUT
          fi 

  this-is-merge-commit:
    needs: process-merge-commit
    runs-on: ubuntu-20.04
    steps:
      - name: Merge commit announce
        if: needs.process-merge-commit.outputs.merge_commit == 'true'
        run: |
          echo "This is a merge commit push. No actions will be runned"

  iac:
    needs: process-merge-commit
    runs-on: ubuntu-20.04
    if: needs.process-merge-commit.outputs.merge_commit == 'false'
    name: Security check for IaaC scripts
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run contract with Snyk to check Infrastructure as Code files for issues
        uses: snyk/actions/iac@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high
          sarif: true
          file: 'help/develop/admin/deploy/cloudformation/cloudformation.json'
      - uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: snyk.sarif
