on:
  push:
    branches:
      - vhlushchenko/GROK-15351-github-notification


jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Slack Failed Build Notification
        uses: rtCamp/action-slack-notify@v2.2.0
        env:
          SLACK_ICON_EMOJI: ':ship:'
          SLACK_USERNAME: BOT
          # SLACK_CHANNEL: githubactions
          SLACK_COLOR: 'danger'
          SLACK_TITLE: 'TESTDeployment'
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_TEST_VLAD }}
    # uses: datagrok-ai/public/.github/workflows/slack_notification.yml@vhlushchenko/GROK-15351-github-notification
    # secrets: inherit
    # with: 
    #   slack_header: "GitHub <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|${{ github.workflow }} ${{ github.run_number }}> failed tests:"
    #   slack_context: true
    #   slack_message_body: "Test results are empty. Probably it was caused by timeout. Check the job output for more information"


    
      