name: Send slack message about action fail
on:
  workflow_run:
    workflows:
      - '*'
    types:
      - completed

jobs:
  notify-on-failure:
    runs-on: ubuntu-latest

    steps:
      - name: Check for failures and send slack notification
        if: ${{ github.event.workflow_run.conclusion == 'failure' }}
        run: |
          SLACK_MESSAGE=$(echo "Workflow failed: ${{ github.event.workflow_run.html_url }}")
          key="${{ github.actor }}"
          value=$(echo '${{ secrets.SLACK_ID }}' | jq -r ".${key}")
          curl -X POST -H 'Content-type: application/json' -H "Authorization: Bearer ${{ secrets.SLACKBOT_TOKEN }}" \
          --data '{"text":"'"${SLACK_MESSAGE}"'", "channel":"'$value'"}' \
          https://slack.com/api/chat.postMessage
