on:
  push:
    branches:
      - vhlushchenko/GROK-15351-github-notification


jobs:
  test-job:
    uses: datagrok-ai/public/.github/workflows/slack_notification.yml@vhlushchenko/GROK-15351-github-notification
    secrets: inherit
    with: 
      slack_header: "GitHub <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|${{ github.workflow }} ${{ github.run_number }}> failed tests:"
      slack_context: true
      slack_message_body: "Test results are empty. Probably it was caused by timeout. Check the job output for more information"


    
      