on:
  push:
    branches:
      - vhlushchenko/GROK-15351-github-notification


jobs:
  slack_notification_test:
    uses: datagrok-ai/public/.github/workflows/slack_notification.yml@vhlushchenko/GROK-15351-github-notification
    with: 
      slack_header: "GitHub <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|${{ github.workflow }} ${{ github.run_number }}> failed tests:"
      slack_context: """*Branch:* <${{ github.server_url }}/${{ github.repository }}/tree/${{ github.ref_name }}|${{ github.ref_name }}>\n*Commit:* <${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}|$(echo ${{ github.sha }} | cut -c1-8) $(git log --format=%B -n 1 ${{ github.sha }} | head -n1 | sed -e 's/"/\\"/g')>"""
      slack_message_body: "Test results are empty. Probably it was caused by timeout. Check the job output for more information"
      slack_token: ${{ secrets.SLACKBOT_TOKEN }}
      slack_id: ${{ secrets.SLACK_ID }}