name: Send slack message about action fail
on:
  workflow_run:
    types:
      - completed

jobs:
  notify-on-failure:
    runs-on: ubuntu-latest

    steps:
      - name: Check for failures
        if: ${{ github.event.workflow_run.conclusion == 'failure' }}
        run: |
          echo "::set-env name=SLACK_MESSAGE::Workflow failed: ${{ github.event.workflow_run.html_url }}"

      - name: Send Slack notification
        if: ${{ env.SLACK_MESSAGE }}
        run: |
          key="${{ github.actor }}"
          value=$(echo "${{ secrets.SLACKBOT_WEBHOOK }}" | jq -r ".${key}")
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text":"'"${SLACK_MESSAGE}"'"}' \
          $value
