name: Tools Package
on:
  workflow_dispatch: {}
  push:
    branches:
      - 'master'
    paths:
      - 'tools/package.json'
jobs:
  build:
    runs-on: ubuntu-20.04
    environment: Prod
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Upgrade npm
        run: npm install -g npm@latest
      - name: npm version
        run: npm version
      - run: npm install
        working-directory: ./tools
#      - run: npm publish
#        working-directory: ./tools
#        env:
#          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Commit package-lock.json
        run: |
          if [ ! -z "$(git status -s tools/package-lock.json)" ]; then
            git config --global user.name 'GitHub Actions'
            git config --global user.email 'githubactions@datagrok.ai'
            git pull
            git add tools/package-lock.json
            git commit -m "GitHub Actions: Update tools/package-lock.json"
            count=0
            until git push; do
              exit=$?
              wait=$((2 ** count))
              count=$((count + 1))
              if [ $count -lt "10" ]; then
                echo "Retry $count/$retries exited $exit, retrying 'git push' in $wait seconds..."
                sleep $wait
                git pull --rebase
              else
                echo "Retry $count/$retries exited $exit, no more retries left for 'git push'."
                exit $exit
              fi
            done
          fi
